name: Feature request
description: Propose an idea
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
